course_name = "服务计算"
course_code = "COMP3017"

notices = ""

[[lecturers]]
name = "Joanna Siebert"
author = { name = "", link = "", date = "" }

textbooks = []

online_resources = []

course = []

[[exam]]
content = """
形式
- Open book 开卷
- Multiple choice questions – 10 questions, 3 points each 单选题！
- Short description questions – 5 questions, 6 points each
- Case questions – 40 points in total
"""
author = { name = "", link = "", date = "" }

lab = []

[[advice]]
content = "有，但不需要读；全靠 PPT 就够了。"
author = { name = "", link = "", date = "" }

schedule = []

[[related_links]]
content = "2023年春笔记：https://github.com/xuanhao44/Service-Computing"
author = { name = "", link = "", date = "" }

misc = []